## Script for calibrating radiocarbon dates with rbacon (bayesian age-depth modelling)

# Load library and set directory ----

source("scripts/functions.R")
library <- c("rbacon")

# Install missing packages
invisible(lapply(library, install_if_missing))

# Load the library
lapply(library, require, character.only = TRUE)

# Get directory where bacon runs are stored
mydir <- normalizePath("data/raw_data/age_data/calibration/Bacon_runs")


# 1) Arabian Peninsula ----

Bacon(coredir=mydir,"Aammiq_Lebanon")
Bacon(coredir=mydir,"Akko_Israel")
Bacon(coredir=mydir,"Al_Balid_2_Oman")
Bacon(coredir=mydir,"Al_Jourd_Lebanon")
Bacon(coredir=mydir,"Al_Hawa_Yemen")
Bacon(coredir=mydir,"Birkat_Ram_Israel")
Bacon(coredir=mydir,"Chamsine_Lebanon")
Bacon(coredir=mydir,"Dor_Israel")
Bacon(coredir=mydir,"Ein_Gedi_Israel", hiatus.depths=1600)
Bacon(coredir=mydir,"Filim_Oman")
Bacon(coredir=mydir,"Ghab_2_Syria")
Bacon(coredir=mydir,"Khor_FB_Qatar")
Bacon(coredir=mydir,"Kinneret_Israel")
Bacon(coredir=mydir,"Kwar_Jaramah_Oman")
Bacon(coredir=mydir,"Mangrove_Suwayh_1_Oman")
Bacon(coredir=mydir,"Palm_Terrace_1_Jordan", postbomb=2)
Bacon(coredir=mydir,"Sumhuran_Oman")
Bacon(coredir=mydir,"Tel_Dan_Israel")
Bacon(coredir=mydir,"Tell_Leilan_Syria", postbomb=2)
Bacon(coredir=mydir,"Tell_Tweini_1_Syria")
Bacon(coredir=mydir,"Tell_Tweini_2_Syria")
Bacon(coredir=mydir,"Huleh_Israel")
Bacon(coredir=mydir,"Mundafan_Saudi_Arabia")
Bacon(coredir=mydir,"Rawri_1_Oman")
Bacon(coredir=mydir,"Tyre_Lebanon")
Bacon(coredir=mydir,"Ein_Gedi_Israel", hiatus.depths=1600)
Bacon(coredir=mydir,"OS73_Oman")
Bacon(coredir=mydir,"MD_9509_Israel")
Bacon(coredir=mydir,"Dead_Sea_7")
Bacon(coredir=mydir,"MD92-1002_Arabian_Sea")
Bacon(coredir=mydir,"Tayma_Saudi_Arabia")

# 2) Mediterranean -----

Bacon(coredir=mydir,"Asi_Gonia_2_Greece", acc.mean=3.5, acc.shape=0.5)  
Bacon(coredir=mydir,"Canada_Cruz_Spain", postbomb = 2)  
Bacon(coredir=mydir,"Lake_Hachlaf_Morocco")  
Bacon(coredir=mydir,"Aanasser_bog_Morocco")  
Bacon(coredir=mydir,"Abant_Golu_Turkey", thick = 10)  
Bacon(coredir=mydir,"Akgol_Adabag_Turkey")  
Bacon(coredir=mydir,"Akotivika_2_Greece")  
Bacon(coredir=mydir,"Akotivika_3_Greece", postbomb = 2)  
Bacon(coredir=mydir,"Albufera_Alcudia_Spain", thick=10)  
Bacon(coredir=mydir,"Algendar_Spain")  
Bacon(coredir=mydir,"Antas_Spain")  
Bacon(coredir=mydir,"Arroyo_Carcavas_Spain")  
Bacon(coredir=mydir,"Arroyo_Navalacarreta_Spain")  
Bacon(coredir=mydir,"Arroyo_Valdeconejos_Spain", postbomb = 2)  
Bacon(coredir=mydir,"Asi_Gonia_1_Greece")  
Bacon(coredir=mydir,"Asi_Gonia_3_Greece")  
Bacon(coredir=mydir,"Bab_El_Karn_Morocco")  
Bacon(coredir=mydir,"Bajondillo_Spain")  
Bacon(coredir=mydir,"Bereket_Turkey", postbomb = 2, thick=10)  
Bacon(coredir=mydir,"Beysehir_Golu_2_Turkey")  
Bacon(coredir=mydir,"Biviere_di_Gela_Italy")  
Bacon(coredir=mydir,"Botija_bog_Spain")  
Bacon(coredir=mydir,"Bourdim_Algeria")  
Bacon(coredir=mydir,"Cala_Galdana_Spain")  
Bacon(coredir=mydir,"Calan_Porter_Spain")  
Bacon(coredir=mydir,"Canaleja_Spain")  
Bacon(coredir=mydir,"Dar_Fatma_Tunisia", hiatus.depths = c(80, 125, 180))  
Bacon(coredir=mydir,"Dayet_MHad_Morocco")  
Bacon(coredir=mydir,"Djebel_Ghorra_2_Tunisia")  
Bacon(coredir=mydir,"Edessa_Greece")  
Bacon(coredir=mydir,"El_Maillo_mire_Spain", postbomb = 2)  
Bacon(coredir=mydir,"El_Sabinar_Spain")  
Bacon(coredir=mydir,"Elx_Spain")  
Bacon(coredir=mydir,"Es_Grau_Spain")  
Bacon(coredir=mydir,"Flambouro_Pieria_Greece")  
Bacon(coredir=mydir,"Garaat_Ouez_Algeria", hiatus.depths = 65)  
Bacon(coredir=mydir,"Giannitsa_B_Greece")  
Bacon(coredir=mydir,"Golhisar_Golu_1_Turkey")  
Bacon(coredir=mydir,"Golhisar_Golu_3_Turkey")  
Bacon(coredir=mydir,"Gorgo_Lungo_Italy")  
Bacon(coredir=mydir,"Gorgo_Tondo_Italy")  
Bacon(coredir=mydir,"Halos_I_Greece")  
Bacon(coredir=mydir,"Ifri_Oudadane_Morocco")  
Bacon(coredir=mydir,"Ioannina_I_Greece")  
Bacon(coredir=mydir,"Ioannina_II_Greece")  
Bacon(coredir=mydir,"Kararmik_Batakligi_Turkey")  
Bacon(coredir=mydir,"Khimaditis_Ib_Greece")  
Bacon(coredir=mydir,"Khimaditis_III_Greece", thick=3)  
Bacon(coredir=mydir,"Koycegiz_Golu_Turkey")  
Bacon(coredir=mydir,"Kucuk_Akgol_Turkey")  
Bacon(coredir=mydir,"Labradillos_mire_Spain")  
Bacon(coredir=mydir,"Lago_Baratz_Italy")  
Bacon(coredir=mydir,"Lago_Venere_Italy")  
Bacon(coredir=mydir,"Lago_Grande_Monticchio_12_Italy", thick=10)  
Bacon(coredir=mydir,"Lago_Grande_Monticchio_13_Italy", thick=5)  
Bacon(coredir=mydir,"Lago_Preola_Italy")  
Bacon(coredir=mydir,"Lago_Trifoglietti_Italy")  
Bacon(coredir=mydir,"Lake_Gramousti_Greece", thick=10)  
Bacon(coredir=mydir,"Lake_Iznik_Turkey")  
Bacon(coredir=mydir,"Lake_Kournas_Greece", thick=10)  
Bacon(coredir=mydir,"Lake_Lerna_1_Greece", postbomb = 2)  
Bacon(coredir=mydir,"Lake_Lerna_2_Greece")  
Bacon(coredir=mydir,"Lake_Manyas_Turkey")  
Bacon(coredir=mydir,"Lake_Orestias_2_Greece")  
Bacon(coredir=mydir,"Lake_Salines_Spain")  
Bacon(coredir=mydir,"Lake_Sapanca_1_Turkey")  
Bacon(coredir=mydir,"Lake_Sidi_Ali_Morocco", thick=10)  
Bacon(coredir=mydir,"Lake_Voulkaria_Greece")  
Bacon(coredir=mydir,"Lake_Xinias_Greece", thick=10)  
Bacon(coredir=mydir,"Lanzahita_Spain")  
Bacon(coredir=mydir,"Larnaca_Salt_Lake_Cyprus")  
Bacon(coredir=mydir,"Las_Lanchas_Spain", thick=1)  
Bacon(coredir=mydir,"Litochoro_Greece")  
Bacon(coredir=mydir,"Majen_Ben_Hmida_Tunisia", hiatus.depths = 175)  
Bacon(coredir=mydir,"Majen_Orbi_1_Tunisia")  
Bacon(coredir=mydir,"Majen_El_Orbi_2_Tunisia", hiatus.depths = 225)  
Bacon(coredir=mydir,"Navarres_2_Spain")  
Bacon(coredir=mydir,"Navarres_3_Spain")  
Bacon(coredir=mydir,"Nile_Delta_S2_Egypt")  
Bacon(coredir=mydir,"Nile_Delta_S6_Egypt")  
Bacon(coredir=mydir,"Nile_Delta_S7_Egypt")  
Bacon(coredir=mydir,"Nile_Delta_S8_Egypt", thick=10)  
Bacon(coredir=mydir,"Nisi_Fen_1_Greece")  
Bacon(coredir=mydir,"Nisi_Fen_2_Greece")  
Bacon(coredir=mydir,"Oumm_el_Khaled_Algeria", thick=2)  
Bacon(coredir=mydir,"Ova_Golu_Turkey")  
Bacon(coredir=mydir,"Patateros_bog_Spain", postbomb = 2, thick=2)  
Bacon(coredir=mydir,"Pego_Oliva_Spain")  
Bacon(coredir=mydir,"Pena_Negra_Spain")  
Bacon(coredir=mydir,"Pertouli_Greece")  
Bacon(coredir=mydir,"Pinarbasi_Turkey")  
Bacon(coredir=mydir,"Praillos_Boissier_mire_Spain", thick=1)  
Bacon(coredir=mydir,"Prat_Vila_Spain")  
Bacon(coredir=mydir,"Puerto_Serranillos_Spain")  
Bacon(coredir=mydir,"Ras_El_Ma_Morocco")  
Bacon(coredir=mydir,"Rezina_marsh_Greece")  
Bacon(coredir=mydir,"Sa_Curcurica_Italy")  
Bacon(coredir=mydir,"San_Rafael_Spain", thick=10)  
Bacon(coredir=mydir,"Sierra_Baza_Spain")  
Bacon(coredir=mydir,"Sierra_Gador_Spain")  
Bacon(coredir=mydir,"Siles_lake_Spain")  
Bacon(coredir=mydir,"Sogut_Gollu_Turkey")  
Bacon(coredir=mydir,"Tigalmamine_Morocco", thick=10)  


# 3) Sahara -----

Bacon(coredir=mydir,"Emi_Koussi_Chad")
Bacon(coredir=mydir,"Baie_Saint_Jean_Mauritania") 
Bacon(coredir=mydir,"Bir_Atrun_Sudan")
Bacon(coredir=mydir,"Chemchane_Mauritania")
Bacon(coredir=mydir,"I_n_Itinen_Algeria")
Bacon(coredir=mydir,"Lake_Yoa_Chad")
Bacon(coredir=mydir,"Mouskorbe_Chad") 
Bacon(coredir=mydir,"Oyo_Sudan")
Bacon(coredir=mydir,"Saqqara_Egypt")
Bacon(coredir=mydir,"Selima_oasis_Sudan")
Bacon(coredir=mydir,"Uan_Afuda_Libya")
Bacon(coredir=mydir,"Uan_Muhuggiag_Libya")
Bacon(coredir=mydir,"Uan_tabu_Libya")
Bacon(coredir=mydir,"Uan_Telocat_Libya")
Bacon(coredir=mydir,"Takarkori_Rock_Shelter_Libya")


# 4) Sub-sahara -----

Bacon(coredir=mydir,"Mboro_Senegal") 
Bacon(coredir=mydir,"Diogo_2_Senegal") 
Bacon(coredir=mydir,"Jikariya_Nigeria") 
Bacon(coredir=mydir,"Kaigama_Nigeria")  
Bacon(coredir=mydir,"Kajemarum_Oasis_Nigeria") 
Bacon(coredir=mydir,"Kuluwu_Oasis_Nigeria") 
Bacon(coredir=mydir,"Lake_Bal_Nigeria")
Bacon(coredir=mydir,"Lake_Chad") 
Bacon(coredir=mydir,"Lake_Hayk_Ethiopia")
Bacon(coredir=mydir,"Lake_Guiers_2_Senegal")
Bacon(coredir=mydir,"Lake_Rkiz_Mauritania", postbomb = 2) 
Bacon(coredir=mydir,"Lake_Tilla_Nigeria") 
Bacon(coredir=mydir,"Lompoul_Senegal") 
Bacon(coredir=mydir,"Mare_Oursi_Burkina_Faso")
Bacon(coredir=mydir,"Ogo_Senegal")
Bacon(coredir=mydir,"Potou_Senegal")  
Bacon(coredir=mydir,"Ravin_Mouche_Mali") 
Bacon(coredir=mydir,"St_Louis_Senegal") 
Bacon(coredir=mydir,"Thiaye_Senegal") 
Bacon(coredir=mydir,"Tjeri_Chad")
Bacon(coredir=mydir,"Touba_Diaye_Senegal", thick=15) 
Bacon(coredir=mydir,"South_El_Obeid_Sudan") 
Bacon(coredir=mydir,"North_Dilling_Sudan") 
Bacon(coredir=mydir,"Badda_bog_Ethiopia") 
Bacon(coredir=mydir,"Bemba_Yanga_Mali") 
Bacon(coredir=mydir,"Dega_Sala_Ethiopia") 
Bacon(coredir=mydir,"Hayla_Cave_Somaliland") 
Bacon(coredir=mydir,"Lake_Abiyata_ABIJATA_Ethiopia") 
Bacon(coredir=mydir,"Lake_Abiyata_ABIYATA_AB5CV_Ethiopia") 
Bacon(coredir=mydir,"Lake_Abiyata_ABIYATA_Ethiopia")
Bacon(coredir=mydir,"Lake_Langeno_LC_Ethiopia") 
Bacon(coredir=mydir,"Mont_Badda_Ethiopia") 
Bacon(coredir=mydir,"Rosilda_Senegal") 
Bacon(coredir=mydir,"Wenchi_Ethiopia") 


# 5) Atlantic Ocean -----

Bacon(coredir=mydir,"M80_17B") 
Bacon(coredir=mydir,"GIK16017-2") 
Bacon(coredir=mydir,"Meteor_12347-2") 
Bacon(coredir=mydir,"Meteor_12345-5") 
Bacon(coredir=mydir,"GeoB9508-5") 
Bacon(coredir=mydir,"GeoB7920-2") 
Bacon(coredir=mydir,"GeoB_9503-5") 
Bacon(coredir=mydir,"A180-48") 
Bacon(coredir=mydir,"GIK12310-4_Atlantic_Ocean")
