## Script for calibrating radiocarbon dates with rbacon (bayesian age-depth modelling)

# Load library and set directory ----

source("scripts/functions.R")
library <- c("rbacon")

# Install missing packages
invisible(lapply(library, install_if_missing))

# Load the library
lapply(library, require, character.only = TRUE)

# Get directory where bacon runs are stored
mydir <- normalizePath("data/raw_data/age_data/calibration/Bacon_runs")

#--------------------------------------------------------#
# 1) Arabian Peninsula ----
#--------------------------------------------------------#

Bacon(coredir=mydir,"Aammiq_Lebanon", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Aammiq_Lebanon/Aammiq_Lebanon_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Akko_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Akko_Israel/Akko_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Al_Balid_2_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Al_Balid_2_Oman/Al_Balid_2_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Al_Jourd_Lebanon", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Al_Jourd_Lebanon/Al_Jourd_Lebanon_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Al_Hawa_Yemen", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Al_Hawa_Yemen/Al_Hawa_Yemen_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Birkat_Ram_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Birkat_Ram_Israel/Birkat_Ram_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Chamsine_Lebanon", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Chamsine_Lebanon/Chamsine_Lebanon_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Dor_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Dor_Israel/Dor_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ein_Gedi_Israel", hiatus.depths=1600, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ein_Gedi_Israel/Ein_Gedi_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Filim_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Filim_Oman/Filim_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ghab_2_Syria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ghab_2_Syria/Ghab_2_Syria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Khor_FB_Qatar", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Khor_FB_Qatar/Khor_FB_Qatar_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kinneret_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kinneret_Israel/Kinneret_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kwar_Jaramah_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kwar_Jaramah_Oman/Kwar_Jaramah_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Mangrove_Suwayh_1_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Mangrove_Suwayh_1_Oman/Mangrove_Suwayh_1_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Palm_Terrace_1_Jordan", postbomb=2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Palm_Terrace_1_Jordan/Palm_Terrace_1_Jordan_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Sumhuran_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Sumhuran_Oman/Sumhuran_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tel_Dan_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tel_Dan_Israel/Tel_Dan_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tell_Leilan_Syria", postbomb=2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tell_Leilan_Syria/Tell_Leilan_Syria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tell_Tweini_1_Syria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tell_Tweini_1_Syria/Tell_Tweini_1_Syria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tell_Tweini_2_Syria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tell_Tweini_2_Syria/Tell_Tweini_2_Syria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Huleh_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Huleh_Israel/Huleh_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Mundafan_Saudi_Arabia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Mundafan_Saudi_Arabia/Mundafan_Saudi_Arabia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Rawri_1_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Rawri_1_Oman/Rawri_1_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tyre_Lebanon", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tyre_Lebanon/Tyre_Lebanon_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"OS73_Oman", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/OS73_Oman/OS73_Oman_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"MD_9509_Israel", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/MD_9509_Israel/MD_9509_Israel_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Dead_Sea_7", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Dead_Sea_7/Dead_Sea_7_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"MD92-1002_Arabian_Sea", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/MD92-1002_Arabian_Sea/MD92-1002_Arabian_Sea_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tayma_Saudi_Arabia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tayma_Saudi_Arabia/Tayma_Saudi_Arabia_depths.txt"),accept.suggestions = TRUE)

#--------------------------------------------------------#
# 2) Mediterranean -----
#--------------------------------------------------------#

Bacon(coredir=mydir,"Asi_Gonia_2_Greece", acc.mean=3.5, acc.shape=0.5, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Asi_Gonia_2_Greece/Asi_Gonia_2_Greece_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Canada_Cruz_Spain", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Canada_Cruz_Spain/Canada_Cruz_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Hachlaf_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Hachlaf_Morocco/Lake_Hachlaf_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Aanasser_bog_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Aanasser_bog_Morocco/Aanasser_bog_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Abant_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Abant_Golu_Turkey/Abant_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Akgol_Adabag_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Akgol_Adabag_Turkey/Akgol_Adabag_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Akotivika_2_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Akotivika_2_Greece/Akotivika_2_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Akotivika_3_Greece", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Akotivika_3_Greece/Akotivika_3_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Albufera_Alcudia_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Albufera_Alcudia_Spain/Albufera_Alcudia_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Algendar_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Algendar_Spain/Algendar_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Antas_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Antas_Spain/Antas_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Arroyo_Carcavas_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Arroyo_Carcavas_Spain/Arroyo_Carcavas_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Arroyo_Navalacarreta_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Arroyo_Navalacarreta_Spain/Arroyo_Navalacarreta_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Arroyo_Valdeconejos_Spain", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Arroyo_Valdeconejos_Spain/Arroyo_Valdeconejos_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Asi_Gonia_1_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Asi_Gonia_1_Greece/Asi_Gonia_1_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Asi_Gonia_3_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Asi_Gonia_3_Greece/Asi_Gonia_3_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Bab_El_Karn_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Bab_El_Karn_Morocco/Bab_El_Karn_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Bajondillo_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Bajondillo_Spain/Bajondillo_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Bereket_Turkey", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Bereket_Turkey/Bereket_Turkey_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Beysehir_Golu_2_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Beysehir_Golu_2_Turkey/Beysehir_Golu_2_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Biviere_di_Gela_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Biviere_di_Gela_Italy/Biviere_di_Gela_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Botija_bog_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Botija_bog_Spain/Botija_bog_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Bourdim_Algeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Bourdim_Algeria/Bourdim_Algeria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Cala_Galdana_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Cala_Galdana_Spain/Cala_Galdana_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Calan_Porter_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Calan_Porter_Spain/Calan_Porter_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Dar_Fatma_Tunisia", hiatus.depths = c(80, 125, 180), depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Dar_Fatma_Tunisia/Dar_Fatma_Tunisia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Dayet_MHad_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Dayet_MHad_Morocco/Dayet_MHad_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Djebel_Ghorra_2_Tunisia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Djebel_Ghorra_2_Tunisia/Djebel_Ghorra_2_Tunisia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Edessa_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Edessa_Greece/Edessa_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"El_Maillo_mire_Spain", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/El_Maillo_mire_Spain/El_Maillo_mire_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"El_Sabinar_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/El_Sabinar_Spain/El_Sabinar_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Elx_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Elx_Spain/Elx_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Es_Grau_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Es_Grau_Spain/Es_Grau_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Flambouro_Pieria_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Flambouro_Pieria_Greece/Flambouro_Pieria_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Garaat_Ouez_Algeria", hiatus.depths = 65, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Garaat_Ouez_Algeria/Garaat_Ouez_Algeria_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Giannitsa_B_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Giannitsa_B_Greece/Giannitsa_B_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Golhisar_Golu_1_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Golhisar_Golu_1_Turkey/Golhisar_Golu_1_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Golhisar_Golu_3_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Golhisar_Golu_3_Turkey/Golhisar_Golu_3_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Gorgo_Lungo_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Gorgo_Lungo_Italy/Gorgo_Lungo_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Gorgo_Tondo_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Gorgo_Tondo_Italy/Gorgo_Tondo_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Halos_I_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Halos_I_Greece/Halos_I_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ifri_Oudadane_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ifri_Oudadane_Morocco/Ifri_Oudadane_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ioannina_I_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ioannina_I_Greece/Ioannina_I_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ioannina_II_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ioannina_II_Greece/Ioannina_II_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kararmik_Batakligi_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kararmik_Batakligi_Turkey/Kararmik_Batakligi_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Khimaditis_Ib_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Khimaditis_Ib_Greece/Khimaditis_Ib_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Khimaditis_III_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Khimaditis_III_Greece/Khimaditis_III_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Koycegiz_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Koycegiz_Golu_Turkey/Koycegiz_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kucuk_Akgol_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kucuk_Akgol_Turkey/Kucuk_Akgol_Turkey_depths.txt"),accept.suggestions = TRUE)  
Bacon(coredir=mydir,"Labradillos_mire_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Labradillos_mire_Spain/Labradillos_mire_Spain_depths.txt"),accept.suggestions = TRUE)  
Bacon(coredir=mydir,"Lago_Baratz_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lago_Baratz_Italy/Lago_Baratz_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lago_Venere_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lago_Venere_Italy/Lago_Venere_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lago_Grande_Monticchio_12_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lago_Grande_Monticchio_12_Italy/Lago_Grande_Monticchio_12_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lago_Grande_Monticchio_13_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lago_Grande_Monticchio_13_Italy/Lago_Grande_Monticchio_13_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lago_Preola_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lago_Preola_Italy/Lago_Preola_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lago_Trifoglietti_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lago_Trifoglietti_Italy/Lago_Trifoglietti_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Gramousti_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Gramousti_Greece/Lake_Gramousti_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Iznik_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Iznik_Turkey/Lake_Iznik_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Kournas_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Kournas_Greece/Lake_Kournas_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Lerna_1_Greece", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Lerna_1_Greece/Lake_Lerna_1_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Lerna_2_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Lerna_2_Greece/Lake_Lerna_2_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Manyas_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Manyas_Turkey/Lake_Manyas_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Orestias_2_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Orestias_2_Greece/Lake_Orestias_2_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Salines_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Salines_Spain/Lake_Salines_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Sidi_Ali_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Sidi_Ali_Morocco/Lake_Sidi_Ali_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Voulkaria_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Voulkaria_Greece/Lake_Voulkaria_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Xinias_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Xinias_Greece/Lake_Xinias_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lanzahita_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lanzahita_Spain/Lanzahita_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Larnaca_Salt_Lake_Cyprus", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Larnaca_Salt_Lake_Cyprus/Larnaca_Salt_Lake_Cyprus_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Las_Lanchas_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Las_Lanchas_Spain/Las_Lanchas_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Litochoro_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Litochoro_Greece/Litochoro_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Majen_Ben_Hmida_Tunisia", hiatus.depths = 175, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Majen_Ben_Hmida_Tunisia/Majen_Ben_Hmida_Tunisia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Majen_Orbi_1_Tunisia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Majen_Orbi_1_Tunisia/Majen_Orbi_1_Tunisia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Majen_El_Orbi_2_Tunisia", hiatus.depths = 225, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Majen_El_Orbi_2_Tunisia/Majen_El_Orbi_2_Tunisia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Navarres_2_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Navarres_2_Spain/Navarres_2_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Navarres_3_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Navarres_3_Spain/Navarres_3_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Nile_Delta_S2_Egypt", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Nile_Delta_S2_Egypt/Nile_Delta_S2_Egypt_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Nile_Delta_S6_Egypt", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Nile_Delta_S6_Egypt/Nile_Delta_S6_Egypt_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Nile_Delta_S7_Egypt", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Nile_Delta_S7_Egypt/Nile_Delta_S7_Egypt_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Nile_Delta_S8_Egypt", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Nile_Delta_S8_Egypt/Nile_Delta_S8_Egypt_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Nisi_Fen_1_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Nisi_Fen_1_Greece/Nisi_Fen_1_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Nisi_Fen_2_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Nisi_Fen_2_Greece/Nisi_Fen_2_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Oumm_el_Khaled_Algeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Oumm_el_Khaled_Algeria/Oumm_el_Khaled_Algeria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ova_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ova_Golu_Turkey/Ova_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Patateros_bog_Spain", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Patateros_bog_Spain/Patateros_bog_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Pego_Oliva_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Pego_Oliva_Spain/Pego_Oliva_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Pena_Negra_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Pena_Negra_Spain/Pena_Negra_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Pertouli_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Pertouli_Greece/Pertouli_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Pinarbasi_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Pinarbasi_Turkey/Pinarbasi_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Praillos_Boissier_mire_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Praillos_Boissier_mire_Spain/Praillos_Boissier_mire_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Prat_Vila_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Prat_Vila_Spain/Prat_Vila_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Puerto_Serranillos_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Puerto_Serranillos_Spain/Puerto_Serranillos_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ras_El_Ma_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ras_El_Ma_Morocco/Ras_El_Ma_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Rezina_marsh_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Rezina_marsh_Greece/Rezina_marsh_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Sa_Curcurica_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Sa_Curcurica_Italy/Sa_Curcurica_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"San_Rafael_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/San_Rafael_Spain/San_Rafael_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Sierra_Baza_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Sierra_Baza_Spain/Sierra_Baza_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Sierra_Gador_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Sierra_Gador_Spain/Sierra_Gador_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Siles_lake_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Siles_lake_Spain/Siles_lake_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Sogut_Gollu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Sogut_Gollu_Turkey/Sogut_Gollu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tigalmamine_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tigalmamine_Morocco/Tigalmamine_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Anavyssos_1_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Anavyssos_1_Greece/Anavyssos_1_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Beliche-Guadiana_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Beliche-Guadiana_Portugal/Beliche-Guadiana_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Burmarrad_ria_Malta", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Burmarrad_ria_Malta/Burmarrad_ria_Malta_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Charca_dos_Coes_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Charca_dos_Coes_Portugal/Charca_dos_Coes_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Charco_da_Candieira_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Charco_da_Candieira_Portugal/Charco_da_Candieira_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Golhisar_Golu_2_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Golhisar_Golu_2_Turkey/Golhisar_Golu_2_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Gorgo_Basso_1_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Gorgo_Basso_1_Italy/Gorgo_Basso_1_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Gorgo_Basso_2_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Gorgo_Basso_2_Italy/Gorgo_Basso_2_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ioannina_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ioannina_Greece/Ioannina_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Katouna_Fen_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Katouna_Fen_Greece/Katouna_Fen_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kaz_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kaz_Golu_Turkey/Kaz_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kopais_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kopais_Greece/Kopais_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ladik_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ladik_Golu_Turkey/Ladik_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lagoa_Clareza_1_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lagoa_Clareza_1_Portugal/Lagoa_Clareza_1_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lagoa_Comprida_1_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lagoa_Comprida_1_Portugal/Lagoa_Comprida_1_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lagoa_Comprida_2_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lagoa_Comprida_2_Portugal/Lagoa_Comprida_2_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lagoa_das_Salgadeiras_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lagoa_das_Salgadeiras_Portugal/Lagoa_das_Salgadeiras_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lagoacho_das_Favas_Portugal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lagoacho_das_Favas_Portugal/Lagoacho_das_Favas_Portugal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Laguna_de_Río_Seco_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Laguna_de_Río_Seco_Spain/Laguna_de_Río_Seco_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Maliq_Albania", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Maliq_Albania/Lake_Maliq_Albania_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Sapanca_1_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Sapanca_1_Turkey/Lake_Sapanca_1_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Limni_Lysimachia_lake_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Limni_Lysimachia_lake_Greece/Limni_Lysimachia_lake_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Limni_Ozeros_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Limni_Ozeros_Greece/Limni_Ozeros_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Maison_Forestiere_1_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Maison_Forestiere_1_Morocco/Maison_Forestiere_1_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Maison_Forestiere_3_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Maison_Forestiere_3_Morocco/Maison_Forestiere_3_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"MD95-2044_Mediterrean_Sea", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/MD95-2044_Mediterrean_Sea/MD95-2044_Mediterrean_Sea_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Merja_Kahla_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Merja_Kahla_Morocco/Merja_Kahla_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Merja_Zerga_Morocco", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Merja_Zerga_Morocco/Merja_Zerga_Morocco_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Padul_1_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Padul_1_Spain/Padul_1_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Psatha_bay_Megaris_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Psatha_bay_Megaris_Greece/Psatha_bay_Megaris_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Roquetas_Mar_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Roquetas_Mar_Spain/Roquetas_Mar_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Son_Bou_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Son_Bou_Spain/Son_Bou_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Stagno_di_Chia_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Stagno_di_Chia_Italy/Stagno_di_Chia_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tecer_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tecer_Golu_Turkey/Tecer_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Tenaghi_Philippon_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tenaghi_Philippon_Greece/Tenaghi_Philippon_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Trikhonis_5_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Trikhonis_5_Greece/Trikhonis_5_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Urgo_Pietra_Giordano_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Urgo_Pietra_Giordano_Italy/Urgo_Pietra_Giordano_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Urio_Quattrocchi_Italy", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Urio_Quattrocchi_Italy/Urio_Quattrocchi_Italy_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Valdeyernos_bog_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Valdeyernos_bog_Spain/Valdeyernos_bog_Spain_depths.txt"), postbomb=2, accept.suggestions = TRUE)
Bacon(coredir=mydir,"Vegoritis_8_Greece", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Vegoritis_8_Greece/Vegoritis_8_Greece_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Villaverde_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Villaverde_Spain/Villaverde_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Yenicaga_Golu_Turkey", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Yenicaga_Golu_Turkey/Yenicaga_Golu_Turkey_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"La_Calderilla_Spain", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/La_Calderilla_Spain/La_Calderilla_Spain_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"M80_17B", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/M80_17B/M80_17B_depths.txt"),accept.suggestions = TRUE) 

#--------------------------------------------------------#
# 3) Sahara -----
#--------------------------------------------------------#

Bacon(coredir=mydir,"Fayium_Oasis_Egypt", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Fayium_Oasis_Egypt/Fayium_Oasis_Egypt_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Emi_Koussi_Chad", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Emi_Koussi_Chad/Emi_Koussi_Chad_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Baie_Saint_Jean_Mauritania", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Baie_Saint_Jean_Mauritania/Baie_Saint_Jean_Mauritania_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Bir_Atrun_Sudan", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Bir_Atrun_Sudan/Bir_Atrun_Sudan_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Chemchane_Mauritania", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Chemchane_Mauritania/Chemchane_Mauritania_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"I_n_Itinen_Algeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/I_n_Itinen_Algeria/I_n_Itinen_Algeria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Yoa_Chad", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Yoa_Chad/Lake_Yoa_Chad_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Mouskorbe_Chad", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Mouskorbe_Chad/Mouskorbe_Chad_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Oyo_Sudan", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Oyo_Sudan/Oyo_Sudan_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Saqqara_Egypt", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Saqqara_Egypt/Saqqara_Egypt_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Selima_oasis_Sudan", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Selima_oasis_Sudan/Selima_oasis_Sudan_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Uan_Afuda_Libya", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Uan_Afuda_Libya/Uan_Afuda_Libya_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Uan_Muhuggiag_Libya", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Uan_Muhuggiag_Libya/Uan_Muhuggiag_Libya_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Uan_tabu_Libya", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Uan_tabu_Libya/Uan_tabu_Libya_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Uan_Telocat_Libya", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Uan_Telocat_Libya/Uan_Telocat_Libya_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Takarkori_Rock_Shelter_Libya", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Takarkori_Rock_Shelter_Libya/Takarkori_Rock_Shelter_Libya_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"GIK12310-4_Atlantic_Ocean", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/GIK12310-4_Atlantic_Ocean/GIK12310-4_Atlantic_Ocean_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"GIK16017-2_Atlantic_Ocean", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/GIK16017-2_Atlantic_Ocean/GIK16017-2_Atlantic_Ocean_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"GeoB7920-2", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/GeoB7920-2/GeoB7920-2_depths.txt"),accept.suggestions = TRUE) 

#--------------------------------------------------------#
# 4) Sub-sahara -----
#--------------------------------------------------------#

Bacon(coredir=mydir,"Mboro_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Mboro_Senegal/Mboro_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Diogo_2_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Diogo_2_Senegal/Diogo_2_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Jikariya_Nigeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Jikariya_Nigeria/Jikariya_Nigeria_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Kaigama_Nigeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kaigama_Nigeria/Kaigama_Nigeria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Kajemarum_Oasis_Nigeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kajemarum_Oasis_Nigeria/Kajemarum_Oasis_Nigeria_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Kuluwu_Oasis_Nigeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Kuluwu_Oasis_Nigeria/Kuluwu_Oasis_Nigeria_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lake_Bal_Nigeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Bal_Nigeria/Lake_Bal_Nigeria_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Chad", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Chad/Lake_Chad_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lake_Hayk_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Hayk_Ethiopia/Lake_Hayk_Ethiopia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Guiers_2_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Guiers_2_Senegal/Lake_Guiers_2_Senegal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Rkiz_Mauritania", postbomb = 2, depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Rkiz_Mauritania/Lake_Rkiz_Mauritania_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lake_Tilla_Nigeria", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Tilla_Nigeria/Lake_Tilla_Nigeria_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lompoul_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lompoul_Senegal/Lompoul_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Mare_Oursi_Burkina_Faso", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Mare_Oursi_Burkina_Faso/Mare_Oursi_Burkina_Faso_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ogo_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ogo_Senegal/Ogo_Senegal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Potou_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Potou_Senegal/Potou_Senegal_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Ravin_Mouche_Mali", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Ravin_Mouche_Mali/Ravin_Mouche_Mali_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"St_Louis_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/St_Louis_Senegal/St_Louis_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Thiaye_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Thiaye_Senegal/Thiaye_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Tjeri_Chad", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Tjeri_Chad/Tjeri_Chad_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Touba_Diaye_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Touba_Diaye_Senegal/Touba_Diaye_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"South_El_Obeid_Sudan", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/South_El_Obeid_Sudan/South_El_Obeid_Sudan_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"North_Dilling_Sudan", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/North_Dilling_Sudan/North_Dilling_Sudan_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Badda_bog_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Badda_bog_Ethiopia/Badda_bog_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Bemba_Yanga_Mali", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Bemba_Yanga_Mali/Bemba_Yanga_Mali_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Dega_Sala_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Dega_Sala_Ethiopia/Dega_Sala_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Hayla_Cave_Somaliland", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Hayla_Cave_Somaliland/Hayla_Cave_Somaliland_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lake_Abiyata_ABIJATA_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Abiyata_ABIJATA_Ethiopia/Lake_Abiyata_ABIJATA_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lake_Abiyata_ABIYATA_AB5CV_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Abiyata_ABIYATA_AB5CV_Ethiopia/Lake_Abiyata_ABIYATA_AB5CV_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Lake_Abiyata_ABIYATA_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Abiyata_ABIYATA_Ethiopia/Lake_Abiyata_ABIYATA_Ethiopia_depths.txt"),accept.suggestions = TRUE)
Bacon(coredir=mydir,"Lake_Langeno_LC_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Lake_Langeno_LC_Ethiopia/Lake_Langeno_LC_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Mont_Badda_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Mont_Badda_Ethiopia/Mont_Badda_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Wenchi_Ethiopia", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Wenchi_Ethiopia/Wenchi_Ethiopia_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Rosilda_Senegal", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Rosilda_Senegal/Rosilda_Senegal_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Meteor_12347-2", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Meteor_12347-2/Meteor_12347-2_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"Meteor_12345-5", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/Meteor_12345-5/Meteor_12345-5_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"GeoB9508-5", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/GeoB9508-5/GeoB9508-5_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"GeoB_9503-5", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/GeoB_9503-5/GeoB_9503-5_depths.txt"),accept.suggestions = TRUE) 
Bacon(coredir=mydir,"A180-48", depths.file= TRUE, depths=read.table("data/raw_data/age_data/calibration/Bacon_runs/A180-48/A180-48_depths.txt"),accept.suggestions = TRUE) 

